# 服务配置
server:
  # 运行模式 debug/release/test
  mode: debug
  # 服务端口
  port: 9091
  # API前缀
  apiPrefix: /api/v1

# 数据库配置
database:
  host: localhost
  port: 3306
  name: mall_order
  username: root
  password: root
  # 是否显示SQL日志
  debug: true
  # 连接池配置
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

# 日志配置
log:
  # 日志级别 debug/info/warn/error/fatal
  level: info
  # 日志文件路径
  filePath: ./logs/order-service.log
  maxDays: 7

# JWT配置
jwt:
  # 签名密钥
  secret: 5gKYk2VZ4fW3bH6jPt8vNxrJqSaL1cEm
  expire: 86400

# 注册中心配置
registry:
  type: consul
  address: localhost:8500
  serviceName: order-service
  tags:
    - order
    - api

# 服务配置
services:
  user:
    name: user-service
    timeout: 5
  product:
    name: product-service
    timeout: 5
  inventory:
    name: inventory-service
    timeout: 5

# 消息队列配置
mq:
  type: rabbitmq
  host: localhost
  port: 5672
  username: guest
  password: guest
  vhost: /
  exchangeName: mall.order
  queueName: mall.order.queue
