server:
  port: 8080
  mode: debug # debug, release, test

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: root
  dbname: mall
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600 # seconds

auth:
  jwt_secret: 5gKYk2VZ4fW3bH6jPt8vNxrJqSaL1cEm
  token_expiry: 86400 # seconds (24 hours)

registry:
  type: consul
  address: localhost:8500
  service_name: user-service
  tags:
    - user
    - api

logging:
  level: info # debug, info, warn, error
  format: json # json, text
  output: stdout # stdout, file
  file_path: ./logs/user-service.log