server:
  port: 8001
  readTimeout: 10
  writeTimeout: 10
  mode: debug

database:
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: password
  database: mall_user
  logLevel: info

jwt:
  secret: mall-user-service-secret-key
  expiration: 1440  # 24小时

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

consul:
  address: localhost:8500
  serviceName: user-service
  tags:
    - go
    - user
    - api
  meta:
    version: v1.0
    environment: dev