version: '3.8'

services:
  # 网关服务
  gateway:
    build:
      context: ../..
      dockerfile: services/gateway-service/Dockerfile
    container_name: mall-gateway
    restart: always
    ports:
      - "8000:8000"
    environment:
      - CONFIG_PATH=/app/configs/config.yaml
    depends_on:
      - mysql
      - redis
      - consul
      - etcd
    networks:
      - mall-network

  # 用户服务
  user-service:
    build:
      context: ../..
      dockerfile: services/user-service/Dockerfile
    container_name: mall-user-service
    restart: always
    environment:
      - CONFIG_PATH=/app/configs/config.docker.yaml
    depends_on:
      - mysql
      - redis
      - consul
    networks:
      - mall-network

  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: mall-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mall
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ../../script/sql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mall-network

  # Redis 缓存
  redis:
    image: redis:6.2-alpine
    container_name: mall-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mall-network

  # Consul 服务发现
  consul:
    image: consul:1.10
    container_name: mall-consul
    restart: always
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - consul-data:/consul/data
    command: agent -server -ui -bootstrap-expect=1 -client=0.0.0.0
    networks:
      - mall-network

  # Etcd 配置中心
  etcd:
    image: bitnami/etcd:3.5
    container_name: mall-etcd
    restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd-data:/bitnami/etcd
    networks:
      - mall-network

  # Nginx 反向代理
  nginx:
    image: nginx:1.21-alpine
    container_name: mall-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../script/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - gateway
    networks:
      - mall-network

volumes:
  mysql-data:
  redis-data:
  consul-data:
  etcd-data:

networks:
  mall-network:
    driver: bridge