server:
  port: "8083"
  mode: "debug"

mongodb:
  uri: "mongodb://localhost:27017"
  database: "oss_db"
  timeout: 10

storage:
  max_upload_size: 10485760 # 10MB
  allowed_types: ["image/jpeg", "image/png", "application/pdf"]
