apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: mall-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: mall-go/gateway-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: CONFIG_PATH
          value: "/app/configs/config.yml"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: CONSUL_ADDRESS
          value: "consul:8500"
        volumeMounts:
        - name: config-volume
          mountPath: /app/configs
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 2
      volumes:
      - name: config-volume
        configMap:
          name: gateway-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: mall-go
spec:
  selector:
    app: gateway-service
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
  namespace: mall-go
data:
  config.yml: |
    server:
      port: 8000
      readTimeout: 10
      writeTimeout: 10
      mode: release

    consul:
      address: consul:8500
      serviceName: gateway-service
      tags:
        - go
        - gateway
        - api
      meta:
        version: v1.0
        environment: prod

    jwt:
      secret: mall-go-gateway-secret-key
      expiration: 1440  # 过期时间，单位分钟

    redis:
      host: redis
      port: 6379
      password: ""
      db: 0

    services:
      user-service:
        path: "/api/users"
        stripPrefix: true
        retries: 3
        timeout: 5  # 超时时间，单位秒
      
      product-service:
        path: "/api/products"
        stripPrefix: true
        retries: 3
        timeout: 5

    rateLimit:
      enabled: true
      type: redis     # 支持 memory 或 redis
      limit: 100      # 默认限流阈值(次/分钟)
      burst: 20       # 突发流量阈值
      endpoints:
        - path: "/api/users"
          limit: 60
          burst: 10
        - path: "/api/products"
          limit: 200
          burst: 50

    cors:
      enabled: true
      allowOrigins:
        - "*"
      allowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowHeaders:
        - Origin
        - Content-Type
        - Accept
        - Authorization
      allowCredentials: true
      maxAge: 86400  # 预检请求有效期，单位秒