apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: mall-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: mall-go/product-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: CONFIG_PATH
          value: "/app/configs/config.yml"
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: CONSUL_ADDRESS
          value: "consul:8500"
        volumeMounts:
        - name: config-volume
          mountPath: /app/configs
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 2
      volumes:
      - name: config-volume
        configMap:
          name: product-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: mall-go
spec:
  selector:
    app: product-service
  ports:
  - port: 8081
    targetPort: 8081
    name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: mall-go
data:
  config.yml: |
    server:
      port: 8081
      readTimeout: 10
      writeTimeout: 10
      mode: release

    database:
      host: mysql
      port: 3306
      username: root
      password: ${MYSQL_PASSWORD}
      database: mall_go

    redis:
      host: redis
      port: 6379
      password: ""
      db: 0

    jwt:
      secret: mall-go-secret-key

    consul:
      address: consul:8500
      serviceName: product-service
      tags:
        - go
        - product
        - api
      meta:
        version: v1.0
        environment: prod