server:
  port: 8000
  mode: debug # debug, release, test

auth:
  jwt_secret: 5gKYk2VZ4fW3bH6jPt8vNxrJqSaL1cEm
  token_expiry: 86400 # seconds (24 hours)

registry:
  type: consul
  address: localhost:8500
  service_name: gateway-service
  tags:
    - gateway
    - api

services:
  user:
    name: user-service
    timeout: 5 # seconds
  # Add other services here as your project grows
  # product:
  #   name: product-service
  #   timeout: 5
  # order:
  #   name: order-service
  #   timeout: 5

rate_limit:
  enabled: true
  requests_per_second: 100
  burst_size: 50

cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Content-Type
    - Authorization
  allow_credentials: true
  max_age: 86400 # seconds

logging:
  level: info # debug, info, warn, error
  format: json # json, text
  output: stdout # stdout, file
  file_path: ./logs/gateway-service.log
