version: '3.8'

services:
  # 网关服务
  gateway:
    build:
      context: ../..
      dockerfile: services/gateway-service/Dockerfile
    container_name: mall-gateway
    restart: always
    ports:
      - "8000:8000"
    environment:
      - CONFIG_PATH=/app/configs/config.yaml
    depends_on:
      - user-service
    networks:
      - mall-network

  # 用户服务
  user-service:
    build:
      context: ../..
      dockerfile: services/user-service/Dockerfile
    container_name: mall-user-service
    restart: always
    environment:
      - CONFIG_PATH=/app/configs/config.docker.yaml
    networks:
      - mall-network

networks:
  mall-network:
    external: true