version: '3.8'

services:
  # MySQL database service
  mysql:
    image: mysql:8.0
    container_name: mall-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mall
    volumes:
      - mysql_data:/var/lib/mysql
      - ../../../script/sql/mall.sql:/docker-entrypoint-initdb.d/mall.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Consul service for service discovery
  consul:
    image: consul:1.15
    container_name: mall-consul
    ports:
      - "8500:8500"
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    volumes:
      - consul_data:/consul/data

  # User service
  user-service:
    build:
      context: ../../..
      dockerfile: services/user-service/Dockerfile
    container_name: mall-user-service
    environment:
      - CONFIG_PATH=/app/configs/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      consul:
        condition: service_started
    volumes:
      - ./configs/config.docker.yaml:/app/configs/config.yaml
    restart: always

volumes:
  mysql_data:
  consul_data: