apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
  namespace: mall-go
spec:
  serviceName: consul
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: consul
        image: consul:1.11
        args:
        - "agent"
        - "-server"
        - "-bootstrap-expect=1"
        - "-ui"
        - "-client=0.0.0.0"
        ports:
        - containerPort: 8500
          name: http
        - containerPort: 8600
          name: dns
        volumeMounts:
        - name: consul-data
          mountPath: /consul/data
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /v1/status/leader
            port: 8500
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v1/status/leader
            port: 8500
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 2
      volumes:
      - name: consul-data
        persistentVolumeClaim:
          claimName: consul-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: mall-go
spec:
  selector:
    app: consul
  ports:
  - name: http
    port: 8500
    targetPort: 8500
  - name: dns
    port: 8600
    targetPort: 8600
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-pvc
  namespace: mall-go
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi