server:
  port: 8081
  readTimeout: 10
  writeTimeout: 10
  mode: debug

database:
  host: localhost
  port: 3306
  username: root
  password: root
  database: mall_go

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret: mall-go-secret-key

consul:
  address: localhost:8500
  serviceName: product-service
  tags:
    - go
    - product
    - api
  meta:
    version: v1.0
    environment: dev

nacos:
  host: localhost
  port: 8848
  namespace: mall-go
  group: DEFAULT_GROUP
  dataID: product-service-config